In [17]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

from datetime import date
from datetime import datetime
import calendar
import os
import re


from scipy import stats
from sklearn.neighbors import KernelDensity
import matplotlib.colors as mcolors
from matplotlib.animation import FuncAnimation, PillowWriter

import seaborn as sns
from pathlib import Path
from tqdm import tqdm_notebook, trange, tqdm
from PIL import Image, ImageDraw
import io
import random as r

from matplotlib.widgets import Slider, Button, RadioButtons
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
# For downsampling
from sklearn.utils import resample,shuffle

In [18]:
df_companies = pd.read_csv("./data/companies.csv")
df_payments = pd.read_csv("./data/payments.csv")
df_physicians = pd.read_csv("./data/physicians.csv")

c:\python38\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (26,27,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [19]:
df_companies.rename({"State":"State_Comp","Country":"Country_Comp"}, axis='columns', inplace=True)
df_physicians.rename({"State":"State_Phys","Country":"Country_Phys"}, axis='columns', inplace=True)
pd.set_option('display.max_columns', None)
df = pd.merge(df_payments, df_physicians, left_on='Physician_ID', right_on='id', how='left').drop('id', axis=1)
df = pd.merge(df, df_companies, on='Company_ID', how='left')
df.rename({"Name":"Company_Name"}, axis='columns', inplace=True)


###test safekeeping dataframe
df_main_test=df[df.set=="test"]

df = df.astype(str)
for column in df.columns:
     if(df[column].dtype=='object'):
        df[column] = df[column].str.lower()

#Convert to Date
df['Date']=pd.to_datetime(df['Date'])

#type conv after str conv
df[['Company_ID','Number_of_Payments']]=df[['Company_ID','Number_of_Payments']].astype(int)
df['Total_Amount_of_Payment_USDollars']=df['Total_Amount_of_Payment_USDollars'].astype(float)

In [20]:
###ENCODING CELL

name_list = pd.unique(df[['Product_Name_1', 'Product_Name_2', 'Product_Name_3']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['Product_Name_1'] = df['Product_Name_1'].apply(product_encode)
df['Product_Name_2'] = df['Product_Name_2'].apply(product_encode)
df['Product_Name_3'] = df['Product_Name_3'].apply(product_encode)

name_list = pd.unique(df[['Product_Code_1', 'Product_Code_2', 'Product_Code_3']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['Product_Code_1'] = df['Product_Code_1'].apply(product_encode)
df['Product_Code_2'] = df['Product_Code_2'].apply(product_encode)
df['Product_Code_3'] = df['Product_Code_3'].apply(product_encode)

name_list = pd.unique(df[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['Product_Category_1'] = df['Product_Category_1'].apply(product_encode)
df['Product_Category_2'] = df['Product_Category_2'].apply(product_encode)
df['Product_Category_3'] = df['Product_Category_3'].apply(product_encode)

name_list = pd.unique(df[['Product_Type_1', 'Product_Type_2','Product_Type_3']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['Product_Type_1'] = df['Product_Type_1'].apply(product_encode)
df['Product_Type_2'] = df['Product_Type_2'].apply(product_encode)
df['Product_Type_3'] = df['Product_Type_3'].apply(product_encode)


name_list = pd.unique(df[['License_State_1', 'License_State_2', 'License_State_3', 'License_State_4', 'License_State_5']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def license_encode(license_state):
    return name_list_dict.get(license_state)

df['License_State_1']=df['License_State_1'].apply(license_encode)
df['License_State_2']=df['License_State_2'].apply(license_encode)
df['License_State_3']=df['License_State_3'].apply(license_encode)
df['License_State_4']=df['License_State_4'].apply(license_encode)
df['License_State_5']=df['License_State_5'].apply(license_encode)

name_list = pd.unique(df[['Country_Comp', 'Country_Phys','Country_of_Travel']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['Country_Comp'] = df['Country_Comp'].apply(product_encode)
df['Country_Phys'] = df['Country_Phys'].apply(product_encode)
df['Country_of_Travel'] = df['Country_of_Travel'].apply(product_encode)

name_list = pd.unique(df[['State_Comp', 'State_Phys', 'State_of_Travel']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['State_Comp'] = df['State_Comp'].apply(product_encode)
df['State_Phys'] = df['State_Phys'].apply(product_encode)
df['State_of_Travel'] = df['State_of_Travel'].apply(product_encode)

name_list = pd.unique(df[['City_of_Travel', 'City']].values.ravel('K'))
# name_list = np.delete(name_list,np.where(name_list=="nan"))
name_list_dict = {}
int_code=int(1)
for name in name_list:
    name_list_dict.update({name:int_code})
    int_code+=1

def product_encode(product_name):
    return name_list_dict.get(product_name)

df['City_of_Travel'] = df['City_of_Travel'].apply(product_encode)
df['City'] = df['City'].apply(product_encode)

df['Ownership_Indicator']=np.where((df.Ownership_Indicator == "yes"),1,df.Ownership_Indicator)
df['Ownership_Indicator']=np.where((df.Ownership_Indicator == "no"),0,df.Ownership_Indicator)
df['Ownership_Indicator']=df['Ownership_Indicator'].astype(int)

df['Date_year']=df['Date'].dt.year
df['Date_month']=df['Date'].dt.month
df['Date_day']=df['Date'].dt.day

columns_encode=['Nature_of_Payment_or_Transfer_of_Value','Form_of_Payment_or_Transfer_of_Value','Zipcode','Third_Party_Recipient', 'Charity', 'Third_Party_Covered','Contextual_Information', 'Related_Product_Indicator','Primary_Specialty']
for column in columns_encode:
    df[column]=df[column].astype('category')
    df[column]=df[column].cat.codes

In [5]:
###DROPPING COLUMNS
df.drop(columns=['Date','Record_ID', 'Physician_ID', 'First_Name', 'Middle_Name', 'Last_Name', 'Name_Suffix', 'Company_Name','Province'],inplace=True)

###SPLIT
df_test=df[df.set=="test"]
df_train=df[df.set=="train"]

###drop set column
df_test.drop(columns=['set'],inplace=True)
df_train.drop(columns=['set'],inplace=True)

##send predicted attribute to end
first_col = df_train.pop("Ownership_Indicator")
df_train.insert((df_train.shape[1]),"Ownership_Indicator",first_col)

first_col = df_test.pop("Ownership_Indicator")
df_test.insert((df_test.shape[1]),"Ownership_Indicator",first_col)

c:\python38\lib\site-packages\pandas\core\frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Internal Accuracy Score 0.9853824066823283
RF accuracy: TRAINING 1.0
RF accuracy: TESTING 0.9856704196519959

In [24]:
###downsampling
df_train_maj=df_train[df_train.Ownership_Indicator==0]
df_train_min=df_train[df_train.Ownership_Indicator==1]
df_train_maj_down=resample(df_train_maj, replace=False, n_samples=df_train_min.shape[0], random_state=2021)
df_train_final = pd.concat([df_train_maj_down, df_train_min])

###test train split of own train set
df_train_final['is_train']=np.random.uniform(0,1,len(df_train_final)) <=.80
train, test = df_train_final[df_train_final['is_train']==True], df_train_final[df_train_final['is_train']==False]
train = shuffle(train)
test = shuffle(test)

In [29]:
features

,Company_ID,Total_Amount_of_Payment_USDollars,Number_of_Payments,Form_of_Payment_or_Transfer_of_Value,Nature_of_Payment_or_Transfer_of_Value,City_of_Travel,State_of_Travel,Country_of_Travel,Third_Party_Recipient,Charity,Third_Party_Covered,Contextual_Information,Related_Product_Indicator,Product_Code_1,Product_Code_2,Product_Code_3,Product_Type_1,Product_Type_2,Product_Type_3,Product_Name_1,Product_Name_2,Product_Name_3,Product_Category_1,Product_Category_2,Product_Category_3,City,State_Phys,Zipcode,Country_Phys,Primary_Specialty,License_State_1,License_State_2,License_State_3,License_State_4,License_State_5,State_Comp,Country_Comp,Date_year,Date_month
10707,712,36.40,5,1,1,1,32,26,1,1,2,29863,4,1,1,1,3,3,3,10,10,10,1,1,1,181,14,977,1,141,8,22,53,53,53,15,1,2013,8
1328605,150,14.22,1,3,8,1,32,26,2,1,0,29736,5,1569,1,1,5,3,3,64,10,10,31,1,1,596,45,2615,1,33,25,53,53,53,53,2,1,2019,8
219656,691,28.00,1,3,13,19,3,1,1,0,2,29736,1,804,1,1,2,3,3,1025,10,10,1,1,1,253,3,4964,1,56,4,53,53,53,53,15,1,2014,8
641634,114,19.71,1,3,8,1,32,26,2,1,0,29736,5,1329,1,1,5,3,3,20,10,10,41,1,1,38,8,5469,1,120,33,53,53,53,53,9,1,2016,6
105368,147,0.14,1,3,8,1,32,26,2,1,0,29736,1,144,1,1,2,3,3,221,10,10,1,1,1,2328,15,2919,1,120,22,3,8,53,53,2,1,2014,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1366359,150,9.03,1,3,8,1,32,26,2,1,0,29736,5,636,1,1,5,3,3,63,10,10,31,1,1,608,6,3020,1,160,6,11,22,12,53,2,1,2019,10
1236329,716,124.00,1,1,5,1,32,26,0,1,1,29758,2,1,1,1,3,3,3,10,10,10,1,1,1,642,21,3155,1,141,22,53,53,53,53,15,1,2019,3
571009,473,24.66,1,3,8,1,32,26,2,1,0,30105,5,1,1,1,4,3,3,3723,10,10,376,1,1,57,16,2520,1,71,1,18,5,53,53,9,1,2016,3
1393721,114,25.00,1,1,13,38,8,1,2,1,0,29736,5,918,1,1,6,3,3,23,10,10,41,1,1,99,46,4743,1,120,40,53,53,53,53,9,1,2019,12
615985,114,20.41,1,3,8,1,32,26,2,1,0,29736,5,918,1329,1,6,5,3,23,20,10,41,41,1,627,45,2587,1,120,10,25,49,53,53,9,1,2016,5

In [26]:
###feature and label split
features=train[train.columns[0:39]]
y=train['Ownership_Indicator']
x_test = test[test.columns[0:39]]
y_test = test['Ownership_Indicator']

###model training
clf = RandomForestClassifier(n_jobs=-1, oob_score = True, n_estimators = 100, random_state=42)

clf.fit(features, y)

# Accuracy Scores
print ('Internal Accuracy Score', clf.oob_score_)
print ('RF accuracy: TRAINING', clf.score(features,y))
print ('RF accuracy: TESTING', clf.score(x_test,y_test))

Internal Accuracy Score 0.9838709677419355
RF accuracy: TRAINING 1.0
RF accuracy: TESTING 0.9906639004149378

In [30]:
phys_id_list=df_main_test['Physician_ID']
phys_id_list

2          2632
10         2401
18         3922
19          896
21          539
           ...
1402236    5046
1402238     473
1402240    4940
1402244    2965
1402248    4495
Name: Physician_ID, Length: 232220, dtype: int64

In [37]:
print(features.columns)
print(df_test.columns)
predict_set=df_test
predict_set.drop(columns=['Date_day', 'Ownership_Indicator'],inplace=True)
print(features.shape)
print(predict_set.shape)

Index(['Company_ID', 'Total_Amount_of_Payment_USDollars', 'Number_of_Payments',
       'Form_of_Payment_or_Transfer_of_Value',
       'Nature_of_Payment_or_Transfer_of_Value', 'City_of_Travel',
       'State_of_Travel', 'Country_of_Travel', 'Third_Party_Recipient',
       'Charity', 'Third_Party_Covered', 'Contextual_Information',
       'Related_Product_Indicator', 'Product_Code_1', 'Product_Code_2',
       'Product_Code_3', 'Product_Type_1', 'Product_Type_2', 'Product_Type_3',
       'Product_Name_1', 'Product_Name_2', 'Product_Name_3',
       'Product_Category_1', 'Product_Category_2', 'Product_Category_3',
       'City', 'State_Phys', 'Zipcode', 'Country_Phys', 'Primary_Specialty',
       'License_State_1', 'License_State_2', 'License_State_3',
       'License_State_4', 'License_State_5', 'State_Comp', 'Country_Comp',
       'Date_year', 'Date_month'],
      dtype='object')
Index(['Company_ID', 'Total_Amount_of_Payment_USDollars', 'Number_of_Payments',
       'Form_of_Payment_or_Transfer_of_Value',
       'Nature_of_Payment_or_Transfer_of_Value', 'City_of_Travel',
       'State_of_Travel', 'Country_of_Travel', 'Third_Party_Recipient',
       'Charity', 'Third_Party_Covered', 'Contextual_Information',
       'Related_Product_Indicator', 'Product_Code_1', 'Product_Code_2',
       'Product_Code_3', 'Product_Type_1', 'Product_Type_2', 'Product_Type_3',
       'Product_Name_1', 'Product_Name_2', 'Product_Name_3',
       'Product_Category_1', 'Product_Category_2', 'Product_Category_3',
       'City', 'State_Phys', 'Zipcode', 'Country_Phys', 'Primary_Specialty',
       'License_State_1', 'License_State_2', 'License_State_3',
       'License_State_4', 'License_State_5', 'State_Comp', 'Country_Comp',
       'Date_year', 'Date_month', 'Date_day', 'Ownership_Indicator'],
      dtype='object')
(3844, 39)
(232220, 39)

c:\python38\lib\site-packages\pandas\core\frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [38]:
score = clf.predict(predict_set)

In [39]:
score.size

232220

In [45]:
# submit={'Physician_ID':phys_id_list, 'Score':score}
# submit_df=pd.DataFrame(data=submit)
submit_df['Physician_ID'].unique().size
physUnique=submit_df['Physician_ID'].unique()
physUnique.size
physUnique[0]

2632

In [51]:

sc=[None]*1000
for i in range(physUnique.size):
    physician=physUnique[i]
    if(submit_df.query('Physician_ID==@physician and Score==1').shape[0]>0):
        sc[i]=1
    else:
        sc[i]=0

In [59]:
final_submit={'Physician_ID':physUnique, 'Score':sc}
fs_df=pd.DataFrame(data=final_submit)
fs_df

     Physician_ID  Score
0            2632      1
1            2401      0
2            3922      0
3             896      0
4             539      0
..            ...    ...
995           136      1
996          1958      1
997          5076      1
998           375      1
999          3876      1

[1000 rows x 2 columns]

In [62]:
fs_df.to_csv("./submission1.csv",index=False)

In [58]:
print(physUnique)
print(sc)

[2632 2401 3922  896  539  562 4437  176 1769 1240 5176 5072 3152 3516
 5665 3148 2019 1685 1084 5429 5421 3390 4662 2177 1554 2073 2098 2264
 5847  655 2681 5766 1144 4537 3998 5143 4541  759 4452 5737 2581 4682
  910 2304 5489  385 2874  974 4872 3926 1794 1199  950 5205  652 2311
 1526  358 4955 1611  877 4535 2154  227  863 3755   81 2763 5953 1102
 1570 2915 3086 3200 3928  442 3248 2416 1566  542 2710 1139 1654 3078
 4133 4951 4742 5572 5597 3386 3359 3610 3064 1466 3393 2321 2272  713
 2424 2406 3447 1103 2533 1870 2586 2241 3595 4597 5908 1917  705 1448
  791 1289  643 2538 3133 3378 5164 4754 3002 1780 2787  379 2441 5410
 5322 5235  251 1792  228 4495 2183 5795 4502 2317 5654 2553 4685 5449
 1982  364 3421 2550 2363 4818 3494 4789 3788  108 1299 2380 2785 2608
 4987 3060 5904 4623 4020 4180 5041 4670 4125 3180 4550 3751 2000 1292
 1175 3311 3287 3010 3743 3674 3561 4031 4571 4700 1329 3798 2568 2122
 4981 1896 3933 3094 5878 2197 1373 3759 3706 5849  104 4093 3705 3825
 3214  316   53 3092 5327 3344 5509 2743  274  992 1840  499 3539 2716
  470 5936 1538 1361  117 2487   47 2265  663 5340 2522 2402 1254 2101
   18 4610 4356 5693 5020 3502 5940 3533 3577  438 1157 2971 4419 3243
 5055 4261  112  714 3392 1994 1143 4100  902 1511 1190 4785 4817 2224
 3090 5819 4528  674 4807 1170   80  419 5114 5097  993 3891 5932 3846
  732  575 2335  540 2354 5046 2966 3911 4015 1779 3937  827 4164 4532
 3970 3316 5629 5284 1618 3012   76  584 2569 5438 3497  383 3594 1044
 4420 3618 1307  473 5195  372 2592 5748 2289 4916 1335 3668 2005 2429
  849 4109 2670 2745 5471 1984 2159 5000 1656 2217 1404 1463 2478 5881
  806 4711 4688  182 3031 3962 3850 1584  508 5339 1693 4753 5764 2928
 4617 4275 3499  309 2425 5439 4895 2367 2037 1719 4564 1215 1323  818
 3909 2305 1727 4213 4011  610 2278 5186 3267 4924 5018 3482 1842  387
  626 3939  703 3166 2325 1785 1326 5118 3785   14 2270 2774 5083  736
 3274  664 5952 3433 3805 5714 1583 2114 1907 2620 5397 2250 1580 4920
 4638   82 5673 1002 1183 5704  698 2956  928 1472 1825 5937 4049  494
 2876 1600 4940 3445  762 1085 3865 3040  139 5875 1787 3047 3023 1837
 3528  485 4098 5575 3756 4277 2026 4813  315 2767 4622 4907 4633 3345
 3001  162 4551 4321 2190 2862  776 2712  407 1303 5257 2531 5365 3582
  868 2546 2157  777 1482 4115 2641 5661 1557 4598  524 5941 4351  476
 4707 5294 4931 1970 1747 1597 5381 2782 2816 3124 1021 2929 5120 5563
 2600 1288 4336  628 2720 2042 5678 4695 3955 5533 5972 4990 2431 2644
 2606 3557 4891 2906 4949 1824 5504 4328 2238 3380 3017 4215 1868 1843
 1723 3597 1971 1057 1434 4069 3657  869 2580 1004  445 3054 3121 4474
 5939 2166 1643 5436 2279 5274 3125 1133 5267 2318   42 4434  109  477
 4340 5915 3879 3228 2705 2277 5237  189 5282 5713 5531 2033 2459  119
 5644 4296  986 3583 3746 4952 3130 4536 4301 5060 4399 1328 5716 5006
 2998 4740 1112 2438 5112 3478 2811  730 2162  395 2242 5797 4152 3789
 1931 3993 3564 3621 5711  965 5592 4721 4312 5602 3847  428 2205 2525
 3041 3042 3744 1405 1673 4844 5335 3503  257 3123  553  883 2136 4945
 4449 5645 5412 2268 5612 1247 1001 2226 5891 4547 1894 1504  186 2870
 3305 2088 5132 1936   58 1527 4104  627 4289 1416  303 4283 3048 1612
 5535 1179 3559 3241 4019  870 2921 4812 3961  398 2765 3971 3391 3609
 4973 4466 3967 2837 1873  680 3826  240 5362 3413 2726  755 5614 5882
 5424 4559  224 2148 2110 3504  995 4851 4719 1433 4900 1436 3063 1678
 1146 4216 4797  187 1376  859 5495 4887 2343 5161 1078 5806 2635 4319
 1308 1543 2893   46  924 1997 1978 5628  963  917 2953 5171 3837  185
 4618 1388 3169   89 1338 3730 3375 2410  155 2214 1128 3949 3496 4587
 2835 3238 4463 3773 1487   90 3991  840 2206 1080 5281  441 3044  223
  671 3530 5319 1248 4004 3540 5517 2128 5561 1124 5075 2866 2104 2235
 1877 5683 2488 5775 3104  335 3548 5933 2741 2115 1898 5001 2963 1961
 1208 2172 5483 3811 5649  636 5860 1423 4947 5865 4308 4605 3995  180
 2830  243 5697 3628 4842 4961 5039 2448 2923 3411 3331   95 4442 2617
  798 2008 1218 3008 3453 2976 2236 2084 3950  637 5144 2361 5583   88
 3795 4516 4314  769 4175  977 2400  306   62 3565  958  532 3135 2375
 5107 4460 5053 3853 4408  287 1946 5964 4002 1725 2938 4506 4883 1046
 3680 2384 3491 3589 5656 2965 4675 1365 5861 4395  673 1115 5499 4478
 1830 4448 1604 3519 1681 2925 5233 4209 5913  265 5136 4766 4467  852
  412 1065 1925 1195 1647 2840 3485 4897 4355 3717 3277 5999 4027 3509
 3216 2195 2780 2927 5244 4826 2118 1933 1881 1648 2544 3188 3535 3641
 1951  452 5835 1098 2056 3581 4135 5549 5959  874 4788  397 2328 3201
 4339 1935 4928 4003 3401 1989 4239 5414  979 5765 1515 1766 4439 3775
   57 1014 4873 3760 4316 3586 3733 3952 3892 4696 3475 5600 1083 4837
 2857 4882 3692 3322 5482 4745 5133  307 3415 3778 4332 3280 3289 3643
  308 1708 1924  613 3251 3659 1097 3739 4374 2724 4989 5088 4464  479
 3035 4859 2790 3647 4366 5594 2074  943 2160 2479 5854  656 2399 2962
 5588 2139 3728 1923 2261  556 4799 2786 1086 5151 4737 1508 3131 2372
  503  337 1048 1185 2630 4606 4367 3976 5715 4091 5101 4327  834 3872
  661  136 1958 5076  375 3876]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1]